# Exported from Render on 2026-01-16T19:31:54Z
version: "1"
services:
- type: web
  name: poker_game_follow_queen
  runtime: python
  repo: https://github.com/mbluecoder2/poker_game_follow_queen
  plan: standard
  envVars:
  - key: FLASK_ENV
    sync: false
  - key: PYTHON_VERSION
    sync: false
  region: virginia
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app
  domains:
  - malajar.com
  - www.malajar.com
  autoDeployTrigger: commit
