services:
  - type: web
    name: poker-follow-queen
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
